### ISSUE TITLE
Top of Deck to Stack cascades entire deck into stack if its the first thing performed in a cockatrice session 

### ISSUE THREAD

**Issue by EonTAS** [ebbit1q/Cockatrice#4]
**System Information:**
Client Version: 2.8.1-custom(b975cfd) (2022-07-04)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.0
System Locale: en_GB
Install Mode: Standard

_______________________________________________________________________________________

Option to move from top of deck to the stack performs a full cascade the first time you try to do it in the session. If you press the cascade varient first it will no longer happen and will not be reproducable until you completely restart cockatrice

Once a proper cascade is performed once it will no longer happen even if you disconnect from a match and connect to a brand new one, so there is an improperly initialised variable or something that preserves between matches.

Example clip
https://streamable.com/qf8ibm 
_______________________________________________________________________________________

Launch cockatrice 
go into a game. 
Press cntrl+y or right click deck and go to the top of deck to stack option,

**Comment by ebbit1q** [comment]
I only noticed now that you've opened a ticket here instead of commenting on the pr this goes with, please see the pr here: https://github.com/Cockatrice/Cockatrice/pull/4648
